query Query {
  introduction {
    fullName
    dateOfBirth
    email
    firstName
    gender
    lastName
    profile {
      description
      career {
        title
        description
        icon
      }
      skill {
        title
        description
        icon
      }
    }
  }
}
