import '@styles/globals.scss'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

import AppHeader from '@/app/_components/header'
import AppFooter from './_components/footer'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const headerProps = {
  profile: "", career: "", skill: "", contact: ""
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body>
        {/* HACK: layoutは一番親として表示される */}
        {/* HACK: layoutは画面遷移の度にレンダリングはされない */}
        <AppHeader title={process.env.NEXT_PUBLIC_ANALYTICS_ID ?? ""} links={headerProps}></AppHeader>
        {children}
        <AppFooter></AppFooter>
      </body>
    </html>
  )
}

